### ISSUE TITLE
# include <torch/extension.h>报错问题

### ISSUE THREAD

**Issue by yyzzyy78** [kwea123/pytorch-cppcuda-tutorial#4]
葵大大您好：
       我在复现程序的过程中遇到了一个问题，就是# include <torch/extension.h>提示no such file or dictionary。我尝试过不同的Python版本，在Python3.8, cuda11.3, pytorch1.12.1, gcc7.5.0环境下仍然没有配置成功。我尝试通过pip或者编译安装了pybind库，或者重新新建工程，但这并没有解决问题。目前通过其他程序可以确认cuda和pytroch-gpu已经正确安装，希望能够获得帮助 ^_^

我的文件和环境配置和如下：
c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/home/yang/anaconda3/envs/cppcuda/include/python3.8",
                "/home/yang/anaconda3/envs/cppcuda/lib/python3.8/site-packages/torch/include",
                "/home/yang/anaconda3/envs/cppcuda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include"
                , "/home/yang/anaconda3/envs/cppcuda/lib/python3.8/site-packages/torch/include/torch/" //extension.h在这里，include仍然报错
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}

interpolation.cpp:
# include <torch/extension.h> //no such file or dictionary

**Comment by atomishcv** [comment]
@yyzzyy78 您好，我也遇到相同的问题，请问您是怎么解决的？

**Comment by atomishcv** [comment]
@yyzzyy78 您好，我在将头文件的路径配置好后，依然出现如下问题：ERROR: Could not build wheels for cppcuda-tutorial, which is required to install pyproject.toml-based projects
请问您有遇到相同的问题吗？

**Comment by p3n-9u1n** [comment]
@yyzzyy78 您好 請問是怎麼解決的呢? 
目前也遇到相同的問題 謝謝您
